### PR TITLE
Reload policy and rate limit settings without restarting daemon

### PR DESCRIPTION
**Pull request by gammazero**
## Context
Use the admin sub-command `reload-config`, or send the daemon process a SIGHUP signal, to reload policy and rate limit settings from the config file.

## Proposed Changes
- New command `admin reload-config` to reload parts of config.
- Handles SIGHUP to signal daemon to reload portions of config.

## Tests
Manual testing for success and failure
 
## Revert Strategy
Change is safe to revert.

### CODE REVIEW

**Review by willscott — COMMENTED** [review]
there are going to be some ops config changes that will also need to happen so that the updated config can be changed against the running pod without triggering a full re-deploy, right?

**Comment by gammazero** [comment]
> there are going to be some ops config changes that will also need to happen so that the updated config can be changed against the running pod without triggering a full re-deploy, right?

There probably should be if it is possible for ops to determine whether a reload is sufficient or whether a full restart is needed.  Currently, reload only reloads the allow/block policy for publishers and providers and reloads rate-limit settings. If there are changes to the config outside of those, then a redeploy is needed. @masih WDYT?

I may be able to reload the entire go-legs subscriber and network servers and registry with more work. Although the more that gets reloaded, the more potential for disruption.

**Comment by gammazero** [comment]
@willscott Even if this does not work with our CI, it still allows us to log into an indexer node and update the policy and rate-limiting without having to restart the indexer.  So, it is still useful for emergencies.

**Comment by masih** [comment]
Right now any change to config will retriever a pod redeployment. This is because the config map is generated and its name contains a short sha of its content, which is then automatically updated in the statefulset manifest that in turn triggers a redeployment. 

I have added a [comment](https://github.com/filecoin-project/storetheindex/issues/485#issuecomment-1139396606) on the related ticket to capture what needs to happen on ops side.

**Comment by gammazero** [comment]
If the daemon is run with the `--watch-config` flag, or the environ var `INDEXER_WATCH_CONFIG` is set, then the indexer will check every 30 seconds to see if the config file has changed. If it has, then it will reload the reloadable sections.

This option is off by default.

**Pull request merged**
